version: '3.10'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/usr/src/app
  test:
    build: .
    volumes:
      - .:/usr/src/app
    command: python -m unittest discover